using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SilverBotDS.Migrations
{
    public partial class transleuitry10 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "translatorSettings",
                columns: table => new
                {
                    Id = table.Column<ulong>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    IsTranslator = table.Column<bool>(type: "INTEGER", nullable: false),
                    CurrentCustomLanguage_Id = table.Column<Guid>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_LangName = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_LangCodeGoogleTranslate = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Hi = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_TimeInUtc = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_CommandIsDisabled = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequestedBy = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_DblaReturnedNull = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_LangCodeForUselessFacts = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_AlreadyConnected = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_UserNotConnected = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_VolumeNotCorrect = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Joined = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NotConnected = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NotPlaying = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NothingInQueue = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NothingInQueueHistory = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SongByAuthor = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RemovedFront = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RemovedXSongOrSongs = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RemovedSong = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RemovedSongs = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_LoopingSong = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_LoopingQueue = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_WrongImageCount = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NotLooping = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NoResults = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Left = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_InformationAbout = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_JoinedSilverCraft = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PrefixUsedTopgg = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_ShuffledSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_User = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Userid = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_IsAnOwner = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_IsABot = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_AccountCreationDate = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_AccountJoinDate = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SilverhostingJokeTitle = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SilverhostingJokeDescription = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PurgeNumberNegative = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PurgeNothingToDelete = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PurgeRemovedFront = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PurgeRemovedSingle = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PurgeRemovedPlural = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NoEmotesFound = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SearchedFor = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_MultipleEmotesFound = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_AlreadyOptedIn = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Server = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_OptedIn = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_OptedInWebshot = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_OptedOutWebshot = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_AllAvailibleEmotes = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_UserIsBannedFromSilversocial = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_UselessFact = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_UserHasLowerRole = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Ban = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Kick = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_BotHasLowerRole = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RandomGif = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PoweredByGiphy = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Meme = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NoImageGeneric = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_EmoteWasLargerThan256K = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_MoreThanOneImageGeneric = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_OutputFileLargerThan8M = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PageGif = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PageGifButtonText = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PageNuget = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PeriodExpired = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_UserIsntBot = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NowPlaying = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Enqueued = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SkippedNP = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_CanForceSkip = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NotPaused = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Voted = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_AlreadyVoted = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_TimeTillTrackPlays = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_TimeWhenTrackPlayed = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SearchFail = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SearchFailTitle = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SearchFailDescription = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Success = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_UrbanExample = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SongLength = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SongTimePosition = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SongTimeLeft = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SongTimeLeftSongLoopingCurrent = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SongTimeLeftSongLooping = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_LoadedSilverBotPlaylistWithTitle = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SongNotExist = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_VersionInfoTitle = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_PurgedBySilverBotReason = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NotValidLanguage = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_CultureInfo = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_BotBannedUser = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_BotKickedUser = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_AddedXAmountOfSongs = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_TrackingStarted = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_TrackingStopped = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_TrackCanNotBeSeeked = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_XPCommandSelf = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_XPCommandOther = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_XPCommandGeneralFail = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_XPCommandLevel = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_XPCommandLevels = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_XPCommandFailSelf = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_XPCommandFailOther = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_XPCommandLeaderBoardTitle = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_XPCommandLeaderBoardPerson = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_DisabledRepeatedPhrases = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_EnableRepeatedPhrases = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_CheckFailed = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_ChecksFailed = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_InvalidOverload = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_GeneralException = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NoMatchingSubcommandsAndGroupNotExecutable = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_QuotePreviewQuoteID = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_QuoteGetNoBook = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_QuoteGetNoQuoteWithId = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_QuotePreviewDeleteSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_HelpCommandHelpString = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_HelpCommandNoDescription = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_HelpCommandGroupCanBeExecuted = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_HelpCommandGroupAliases = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_HelpCommandGroupArguments = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_HelpCommandGroupSubcommands = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_HelpCommandGroupListingAllCommands = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireDJCheckFailed = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireGuildCheckFailed = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireNsfwCheckFailed = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireOwnerCheckFailed = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireRolesCheckFailedSG = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireRolesCheckFailedPL = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireBotPermisionsCheckFailedPL = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireBotPermisionsCheckFailedSG = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireUserPermisionsCheckFailedPL = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireUserPermisionsCheckFailedSG = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireBotAndUserPermisionsCheckFailedPL = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_RequireBotAndUserPermisionsCheckFailedSG = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_UnknownImageFormat = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_JpegSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SilverSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_ComicSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_ResizeSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_TintSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_MathSteps = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Results = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SomethingsContributors = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NuGetVerified = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Type = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Downloads = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_Version = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SetToProvidedStrings = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_SetToDefaultStrings = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NoPerm = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_CategorySetSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_EmojiMessageDownloadStart = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_EmojiMessageDownloadEnd = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_EmojiEnd = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_FreeToPlayGameType = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NotAvailableGameType = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_CostsMoneyGameTypeBug = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NoGamesWereReturned = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_NoGamesWereReturnedDescription = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_AmericanMoney = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_OS = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_DsharpplusVersion = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_VersionNumber = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_GitRepo = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_GitCommitHash = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_GitBranch = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_IsDirty = table.Column<string>(type: "TEXT", nullable: true),
                    CurrentCustomLanguage_CLR = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_translatorSettings", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "translatorSettings_CustomLanguages",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "TEXT", nullable: false),
                    TranslatorSettingsId = table.Column<ulong>(type: "INTEGER", nullable: false),
                    LangName = table.Column<string>(type: "TEXT", nullable: true),
                    LangCodeGoogleTranslate = table.Column<string>(type: "TEXT", nullable: true),
                    Hi = table.Column<string>(type: "TEXT", nullable: true),
                    TimeInUtc = table.Column<string>(type: "TEXT", nullable: true),
                    CommandIsDisabled = table.Column<string>(type: "TEXT", nullable: true),
                    RequestedBy = table.Column<string>(type: "TEXT", nullable: true),
                    DblaReturnedNull = table.Column<string>(type: "TEXT", nullable: true),
                    LangCodeForUselessFacts = table.Column<string>(type: "TEXT", nullable: true),
                    AlreadyConnected = table.Column<string>(type: "TEXT", nullable: true),
                    UserNotConnected = table.Column<string>(type: "TEXT", nullable: true),
                    VolumeNotCorrect = table.Column<string>(type: "TEXT", nullable: true),
                    Joined = table.Column<string>(type: "TEXT", nullable: true),
                    NotConnected = table.Column<string>(type: "TEXT", nullable: true),
                    NotPlaying = table.Column<string>(type: "TEXT", nullable: true),
                    NothingInQueue = table.Column<string>(type: "TEXT", nullable: true),
                    NothingInQueueHistory = table.Column<string>(type: "TEXT", nullable: true),
                    SongByAuthor = table.Column<string>(type: "TEXT", nullable: true),
                    RemovedFront = table.Column<string>(type: "TEXT", nullable: true),
                    RemovedXSongOrSongs = table.Column<string>(type: "TEXT", nullable: true),
                    RemovedSong = table.Column<string>(type: "TEXT", nullable: true),
                    RemovedSongs = table.Column<string>(type: "TEXT", nullable: true),
                    LoopingSong = table.Column<string>(type: "TEXT", nullable: true),
                    LoopingQueue = table.Column<string>(type: "TEXT", nullable: true),
                    WrongImageCount = table.Column<string>(type: "TEXT", nullable: true),
                    NotLooping = table.Column<string>(type: "TEXT", nullable: true),
                    NoResults = table.Column<string>(type: "TEXT", nullable: true),
                    Left = table.Column<string>(type: "TEXT", nullable: true),
                    InformationAbout = table.Column<string>(type: "TEXT", nullable: true),
                    JoinedSilverCraft = table.Column<string>(type: "TEXT", nullable: true),
                    PrefixUsedTopgg = table.Column<string>(type: "TEXT", nullable: true),
                    ShuffledSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    User = table.Column<string>(type: "TEXT", nullable: true),
                    Userid = table.Column<string>(type: "TEXT", nullable: true),
                    IsAnOwner = table.Column<string>(type: "TEXT", nullable: true),
                    IsABot = table.Column<string>(type: "TEXT", nullable: true),
                    AccountCreationDate = table.Column<string>(type: "TEXT", nullable: true),
                    AccountJoinDate = table.Column<string>(type: "TEXT", nullable: true),
                    SilverhostingJokeTitle = table.Column<string>(type: "TEXT", nullable: true),
                    SilverhostingJokeDescription = table.Column<string>(type: "TEXT", nullable: true),
                    PurgeNumberNegative = table.Column<string>(type: "TEXT", nullable: true),
                    PurgeNothingToDelete = table.Column<string>(type: "TEXT", nullable: true),
                    PurgeRemovedFront = table.Column<string>(type: "TEXT", nullable: true),
                    PurgeRemovedSingle = table.Column<string>(type: "TEXT", nullable: true),
                    PurgeRemovedPlural = table.Column<string>(type: "TEXT", nullable: true),
                    NoEmotesFound = table.Column<string>(type: "TEXT", nullable: true),
                    SearchedFor = table.Column<string>(type: "TEXT", nullable: true),
                    MultipleEmotesFound = table.Column<string>(type: "TEXT", nullable: true),
                    AlreadyOptedIn = table.Column<string>(type: "TEXT", nullable: true),
                    Server = table.Column<string>(type: "TEXT", nullable: true),
                    OptedIn = table.Column<string>(type: "TEXT", nullable: true),
                    OptedInWebshot = table.Column<string>(type: "TEXT", nullable: true),
                    OptedOutWebshot = table.Column<string>(type: "TEXT", nullable: true),
                    AllAvailibleEmotes = table.Column<string>(type: "TEXT", nullable: true),
                    UserIsBannedFromSilversocial = table.Column<string>(type: "TEXT", nullable: true),
                    UselessFact = table.Column<string>(type: "TEXT", nullable: true),
                    UserHasLowerRole = table.Column<string>(type: "TEXT", nullable: true),
                    Ban = table.Column<string>(type: "TEXT", nullable: true),
                    Kick = table.Column<string>(type: "TEXT", nullable: true),
                    BotHasLowerRole = table.Column<string>(type: "TEXT", nullable: true),
                    RandomGif = table.Column<string>(type: "TEXT", nullable: true),
                    PoweredByGiphy = table.Column<string>(type: "TEXT", nullable: true),
                    Meme = table.Column<string>(type: "TEXT", nullable: true),
                    NoImageGeneric = table.Column<string>(type: "TEXT", nullable: true),
                    EmoteWasLargerThan256K = table.Column<string>(type: "TEXT", nullable: true),
                    MoreThanOneImageGeneric = table.Column<string>(type: "TEXT", nullable: true),
                    OutputFileLargerThan8M = table.Column<string>(type: "TEXT", nullable: true),
                    PageGif = table.Column<string>(type: "TEXT", nullable: true),
                    PageGifButtonText = table.Column<string>(type: "TEXT", nullable: true),
                    PageNuget = table.Column<string>(type: "TEXT", nullable: true),
                    PeriodExpired = table.Column<string>(type: "TEXT", nullable: true),
                    UserIsntBot = table.Column<string>(type: "TEXT", nullable: true),
                    NowPlaying = table.Column<string>(type: "TEXT", nullable: true),
                    Enqueued = table.Column<string>(type: "TEXT", nullable: true),
                    SkippedNP = table.Column<string>(type: "TEXT", nullable: true),
                    CanForceSkip = table.Column<string>(type: "TEXT", nullable: true),
                    NotPaused = table.Column<string>(type: "TEXT", nullable: true),
                    Voted = table.Column<string>(type: "TEXT", nullable: true),
                    AlreadyVoted = table.Column<string>(type: "TEXT", nullable: true),
                    TimeTillTrackPlays = table.Column<string>(type: "TEXT", nullable: true),
                    TimeWhenTrackPlayed = table.Column<string>(type: "TEXT", nullable: true),
                    SearchFail = table.Column<string>(type: "TEXT", nullable: true),
                    SearchFailTitle = table.Column<string>(type: "TEXT", nullable: true),
                    SearchFailDescription = table.Column<string>(type: "TEXT", nullable: true),
                    Success = table.Column<string>(type: "TEXT", nullable: true),
                    UrbanExample = table.Column<string>(type: "TEXT", nullable: true),
                    SongLength = table.Column<string>(type: "TEXT", nullable: true),
                    SongTimePosition = table.Column<string>(type: "TEXT", nullable: true),
                    SongTimeLeft = table.Column<string>(type: "TEXT", nullable: true),
                    SongTimeLeftSongLoopingCurrent = table.Column<string>(type: "TEXT", nullable: true),
                    SongTimeLeftSongLooping = table.Column<string>(type: "TEXT", nullable: true),
                    LoadedSilverBotPlaylistWithTitle = table.Column<string>(type: "TEXT", nullable: true),
                    SongNotExist = table.Column<string>(type: "TEXT", nullable: true),
                    VersionInfoTitle = table.Column<string>(type: "TEXT", nullable: true),
                    PurgedBySilverBotReason = table.Column<string>(type: "TEXT", nullable: true),
                    NotValidLanguage = table.Column<string>(type: "TEXT", nullable: true),
                    CultureInfo = table.Column<string>(type: "TEXT", nullable: true),
                    BotBannedUser = table.Column<string>(type: "TEXT", nullable: true),
                    BotKickedUser = table.Column<string>(type: "TEXT", nullable: true),
                    AddedXAmountOfSongs = table.Column<string>(type: "TEXT", nullable: true),
                    TrackingStarted = table.Column<string>(type: "TEXT", nullable: true),
                    TrackingStopped = table.Column<string>(type: "TEXT", nullable: true),
                    TrackCanNotBeSeeked = table.Column<string>(type: "TEXT", nullable: true),
                    XPCommandSelf = table.Column<string>(type: "TEXT", nullable: true),
                    XPCommandOther = table.Column<string>(type: "TEXT", nullable: true),
                    XPCommandGeneralFail = table.Column<string>(type: "TEXT", nullable: true),
                    XPCommandLevel = table.Column<string>(type: "TEXT", nullable: true),
                    XPCommandLevels = table.Column<string>(type: "TEXT", nullable: true),
                    XPCommandFailSelf = table.Column<string>(type: "TEXT", nullable: true),
                    XPCommandFailOther = table.Column<string>(type: "TEXT", nullable: true),
                    XPCommandLeaderBoardTitle = table.Column<string>(type: "TEXT", nullable: true),
                    XPCommandLeaderBoardPerson = table.Column<string>(type: "TEXT", nullable: true),
                    DisabledRepeatedPhrases = table.Column<string>(type: "TEXT", nullable: true),
                    EnableRepeatedPhrases = table.Column<string>(type: "TEXT", nullable: true),
                    CheckFailed = table.Column<string>(type: "TEXT", nullable: true),
                    ChecksFailed = table.Column<string>(type: "TEXT", nullable: true),
                    InvalidOverload = table.Column<string>(type: "TEXT", nullable: true),
                    GeneralException = table.Column<string>(type: "TEXT", nullable: true),
                    NoMatchingSubcommandsAndGroupNotExecutable = table.Column<string>(type: "TEXT", nullable: true),
                    QuotePreviewQuoteID = table.Column<string>(type: "TEXT", nullable: true),
                    QuoteGetNoBook = table.Column<string>(type: "TEXT", nullable: true),
                    QuoteGetNoQuoteWithId = table.Column<string>(type: "TEXT", nullable: true),
                    QuotePreviewDeleteSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    HelpCommandHelpString = table.Column<string>(type: "TEXT", nullable: true),
                    HelpCommandNoDescription = table.Column<string>(type: "TEXT", nullable: true),
                    HelpCommandGroupCanBeExecuted = table.Column<string>(type: "TEXT", nullable: true),
                    HelpCommandGroupAliases = table.Column<string>(type: "TEXT", nullable: true),
                    HelpCommandGroupArguments = table.Column<string>(type: "TEXT", nullable: true),
                    HelpCommandGroupSubcommands = table.Column<string>(type: "TEXT", nullable: true),
                    HelpCommandGroupListingAllCommands = table.Column<string>(type: "TEXT", nullable: true),
                    RequireDJCheckFailed = table.Column<string>(type: "TEXT", nullable: true),
                    RequireGuildCheckFailed = table.Column<string>(type: "TEXT", nullable: true),
                    RequireNsfwCheckFailed = table.Column<string>(type: "TEXT", nullable: true),
                    RequireOwnerCheckFailed = table.Column<string>(type: "TEXT", nullable: true),
                    RequireRolesCheckFailedSG = table.Column<string>(type: "TEXT", nullable: true),
                    RequireRolesCheckFailedPL = table.Column<string>(type: "TEXT", nullable: true),
                    RequireBotPermisionsCheckFailedPL = table.Column<string>(type: "TEXT", nullable: true),
                    RequireBotPermisionsCheckFailedSG = table.Column<string>(type: "TEXT", nullable: true),
                    RequireUserPermisionsCheckFailedPL = table.Column<string>(type: "TEXT", nullable: true),
                    RequireUserPermisionsCheckFailedSG = table.Column<string>(type: "TEXT", nullable: true),
                    RequireBotAndUserPermisionsCheckFailedPL = table.Column<string>(type: "TEXT", nullable: true),
                    RequireBotAndUserPermisionsCheckFailedSG = table.Column<string>(type: "TEXT", nullable: true),
                    UnknownImageFormat = table.Column<string>(type: "TEXT", nullable: true),
                    JpegSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    SilverSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    ComicSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    ResizeSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    TintSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    MathSteps = table.Column<string>(type: "TEXT", nullable: true),
                    Results = table.Column<string>(type: "TEXT", nullable: true),
                    SomethingsContributors = table.Column<string>(type: "TEXT", nullable: true),
                    NuGetVerified = table.Column<string>(type: "TEXT", nullable: true),
                    Type = table.Column<string>(type: "TEXT", nullable: true),
                    Downloads = table.Column<string>(type: "TEXT", nullable: true),
                    Version = table.Column<string>(type: "TEXT", nullable: true),
                    SetToProvidedStrings = table.Column<string>(type: "TEXT", nullable: true),
                    SetToDefaultStrings = table.Column<string>(type: "TEXT", nullable: true),
                    NoPerm = table.Column<string>(type: "TEXT", nullable: true),
                    CategorySetSuccess = table.Column<string>(type: "TEXT", nullable: true),
                    EmojiMessageDownloadStart = table.Column<string>(type: "TEXT", nullable: true),
                    EmojiMessageDownloadEnd = table.Column<string>(type: "TEXT", nullable: true),
                    EmojiEnd = table.Column<string>(type: "TEXT", nullable: true),
                    FreeToPlayGameType = table.Column<string>(type: "TEXT", nullable: true),
                    NotAvailableGameType = table.Column<string>(type: "TEXT", nullable: true),
                    CostsMoneyGameTypeBug = table.Column<string>(type: "TEXT", nullable: true),
                    NoGamesWereReturned = table.Column<string>(type: "TEXT", nullable: true),
                    NoGamesWereReturnedDescription = table.Column<string>(type: "TEXT", nullable: true),
                    AmericanMoney = table.Column<string>(type: "TEXT", nullable: true),
                    OS = table.Column<string>(type: "TEXT", nullable: true),
                    DsharpplusVersion = table.Column<string>(type: "TEXT", nullable: true),
                    VersionNumber = table.Column<string>(type: "TEXT", nullable: true),
                    GitRepo = table.Column<string>(type: "TEXT", nullable: true),
                    GitCommitHash = table.Column<string>(type: "TEXT", nullable: true),
                    GitBranch = table.Column<string>(type: "TEXT", nullable: true),
                    IsDirty = table.Column<string>(type: "TEXT", nullable: true),
                    CLR = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_translatorSettings_CustomLanguages", x => new { x.TranslatorSettingsId, x.Id });
                    table.ForeignKey(
                        name: "FK_translatorSettings_CustomLanguages_translatorSettings_TranslatorSettingsId",
                        column: x => x.TranslatorSettingsId,
                        principalTable: "translatorSettings",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "translatorSettings_CustomLanguages");

            migrationBuilder.DropTable(
                name: "translatorSettings");
        }
    }
}
